from __future__ import annotations


def attach(subparsers, *, ctx) -> None:
    task_parser = subparsers.add_parser("task")
    task_sub = task_parser.add_subparsers(dest="task_command", required=True)

    task_create = task_sub.add_parser("create")
    task_create.add_argument("title")
    task_create.add_argument("--slug")
    task_create.add_argument("--description")
    task_create.add_argument("--priority", type=int, default=2)
    task_create.add_argument("--created-by")
    task_create.add_argument("--parent-task", type=int)
    task_create.add_argument("--delegation-mode", default="direct", choices=["direct", "hypervisor"])
    task_create.add_argument("--path", action="append")
    task_create.add_argument("--force-role-override", action="store_true")
    task_create.set_defaults(func=ctx.cmd_task_create)

    task_list = task_sub.add_parser("list")
    task_list.add_argument("--json", action="store_true")
    task_list.set_defaults(func=ctx.cmd_task_list)

    task_show = task_sub.add_parser("show")
    task_show.add_argument("task_id", type=int)
    task_show.add_argument("--agent")
    task_show.add_argument("--json", action="store_true")
    task_show.set_defaults(func=ctx.cmd_task_show)

    task_claim = task_sub.add_parser("claim")
    task_claim.add_argument("task_id", type=int)
    task_claim.add_argument("agent")
    task_claim.add_argument("--ttl-minutes", type=int, default=30)
    task_claim.add_argument("--force-role-override", action="store_true")
    task_claim.add_argument("--strict", action="store_true", help="block claim on path conflict instead of warning")
    task_claim.set_defaults(func=ctx.cmd_task_claim)

    task_priority = task_sub.add_parser("priority")
    task_priority.add_argument("task_id", type=int)
    task_priority.add_argument("agent")
    task_priority.add_argument("priority", type=int)
    task_priority.add_argument("--force-role-override", action="store_true")
    task_priority.set_defaults(func=ctx.cmd_task_update_priority)

    task_delegate = task_sub.add_parser("delegate")
    task_delegate.add_argument("parent_task_id", type=int)
    task_delegate.add_argument("owner_agent")
    task_delegate.add_argument("assignee_agent")
    task_delegate.add_argument("title")
    task_delegate.add_argument("--slug")
    task_delegate.add_argument("--description")
    task_delegate.add_argument("--subject")
    task_delegate.add_argument("--body", required=True)
    task_delegate.add_argument("--priority", type=int)
    task_delegate.add_argument("--ttl-minutes", type=int, default=30)
    task_delegate.add_argument("--path", action="append")
    task_delegate.add_argument("--force-role-override", action="store_true")
    task_delegate.set_defaults(func=ctx.cmd_task_delegate)

    task_status = task_sub.add_parser("status")
    task_status.add_argument("task_id", type=int)
    task_status.add_argument("agent")
    task_status.add_argument("status")
    task_status.add_argument("--force-role-override", action="store_true")
    task_status.set_defaults(func=ctx.cmd_task_update_status)

    task_handoff = task_sub.add_parser("handoff")
    task_handoff.add_argument("task_id", type=int)
    task_handoff.add_argument("from_agent")
    task_handoff.add_argument("to_agent")
    task_handoff.add_argument("--subject")
    task_handoff.add_argument("--body", required=True)
    task_handoff.add_argument("--force-role-override", action="store_true")
    task_handoff.set_defaults(func=ctx.cmd_task_handoff)

    lease_parser = subparsers.add_parser("lease")
    lease_sub = lease_parser.add_subparsers(dest="lease_command", required=True)

    lease_renew = lease_sub.add_parser("renew")
    lease_renew.add_argument("task_id", type=int)
    lease_renew.add_argument("agent")
    lease_renew.add_argument("--ttl-minutes", type=int, default=30)
    lease_renew.set_defaults(func=ctx.cmd_lease_renew)
